using System.Collections.Generic;
using System.IO;
using Sandbox.ModAPI;

namespace HostileTakeover2.Thraxus.Utility.Classification
{
    internal static class BlockClassificationWriter
    {
        private const string FileName = "BlockClassification.xml";

        public static void Write(BlockClassificationData data)
        {
            var control = new List<string>(data.ControlBlocks);
            var medical = new List<string>(data.MedicalBlocks);
            var weapon  = new List<string>(data.WeaponBlocks);
            var trap    = new List<string>(data.TrapBlocks);

            control.Sort();
            medical.Sort();
            weapon.Sort();
            trap.Sort();

            using (TextWriter w = MyAPIGateway.Utilities.WriteFileInLocalStorage(FileName, typeof(BlockClassificationWriter)))
            {
                w.WriteLine("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
                w.WriteLine("<!--");
                w.WriteLine("  Generated by HostileTakeover2 on session load. Overwritten every session.");
                w.WriteLine("  This file is read-only. To customize, use BlockClassificationOverrides.xml.");
                w.WriteLine("-->");
                w.WriteLine("<BlockClassification>");
                w.WriteLine();
                WriteSection(w, "ControlBlocks", control);
                WriteSection(w, "MedicalBlocks", medical);
                WriteSection(w, "WeaponBlocks",  weapon);
                WriteSection(w, "TrapBlocks",    trap);
                w.Write("</BlockClassification>");
            }
        }

        private static void WriteSection(TextWriter w, string tag, List<string> blocks)
        {
            w.WriteLine($"  <{tag} count=\"{blocks.Count}\">");
            foreach (var block in blocks)
                w.WriteLine($"    <Block>{block}</Block>");
            w.WriteLine($"  </{tag}>");
            w.WriteLine();
        }
    }
}
